package paul.tables;
// Generated Apr 2, 2016 10:15:00 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderdetails generated by hbm2java
 */
@Entity
@Table(name = "orderdetails")
public class Orderdetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4535513145084518574L;
	private OrderdetailsId id;
	private Orders orders;
	private Products products;
	private int quantityOrdered;
	private double priceEach;
	private short orderLineNumber;

	public Orderdetails() {
	}

	public Orderdetails(OrderdetailsId id, Orders orders, Products products, int quantityOrdered, double priceEach,
			short orderLineNumber) {
		this.id = id;
		this.orders = orders;
		this.products = products;
		this.quantityOrdered = quantityOrdered;
		this.priceEach = priceEach;
		this.orderLineNumber = orderLineNumber;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderNumber", column = @Column(name = "orderNumber", nullable = false)),
			@AttributeOverride(name = "productCode", column = @Column(name = "productCode", nullable = false, length = 15)) })
	public OrderdetailsId getId() {
		return this.id;
	}

	public void setId(OrderdetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderNumber", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productCode", nullable = false, insertable = false, updatable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "quantityOrdered", nullable = false)
	public int getQuantityOrdered() {
		return this.quantityOrdered;
	}

	public void setQuantityOrdered(int quantityOrdered) {
		this.quantityOrdered = quantityOrdered;
	}

	@Column(name = "priceEach", nullable = false, precision = 22, scale = 0)
	public double getPriceEach() {
		return this.priceEach;
	}

	public void setPriceEach(double priceEach) {
		this.priceEach = priceEach;
	}

	@Column(name = "orderLineNumber", nullable = false)
	public short getOrderLineNumber() {
		return this.orderLineNumber;
	}

	public void setOrderLineNumber(short orderLineNumber) {
		this.orderLineNumber = orderLineNumber;
	}

}
